name: build rust9x toolchain

env:
  COMPRESSION_LV: 5
  COMPRESSION_ALGO: LZMA2
  PACKED_FILE: rust9x.7z
  DIGEST_FILE: sha256sum.txt
  BUILD_CACHE_KEY: Windows-build
  DIST_CACHE_KEY: dist

on:
  push:
    tags:
      - "*.*"
jobs:
  build:
    runs-on: windows-latest
    outputs:
      dist_dir: ${{ steps.get_dist_dir.outputs.dist }}
      comparation: ${{ steps.get_dist_dir.outputs.comparation }}
    steps:
      - uses: actions/checkout@v4
        with:
          # repository: rust9x/rust
          ref: rust9x
          fetch-depth: 50
          # submodules: true

      - name: get dist dir
        id: get_dist_dir
        env:
          # api: ${{ format('https://api.github.com/repos/rust9x/rust/releases') }}
          api: ${{ format('https://api.github.com/repos/{0}/releases', github.repository) }}
        run: |
          Set-Location -Path ..
          $dist = "$(Get-Location)\dist"
          "dist=$dist" >> $GITHUB_OUTPUT
          "DIST=$dist" >> $env:GITHUB_ENV

      - name: restore build-cache
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: build
          key: ${{ env.BUILD_CACHE_KEY }}

      - name: remove link & list directory
        continue-on-error: true
        run: |
          Remove-Item -Path build\host -Force
          Get-ChildItem -Depth 1 -Path build

      - name: build 9x
        run: |
          Copy-Item -Path config.rust9x.toml -Destination config.toml -Force
          python x.py install --verbose

      - name: list the dist directory
        run: |
          Get-ChildItem -Depth 1 -Path ${{ env.DIST }}

      - name: delete old cache
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        uses: MyAlbum/purge-cache@v2
        with:
          debug: true
          max-age: 60

      - name: save dist-cache
        uses: actions/cache/save@v3
        with:
          path: ${{ env.DIST }}
          key: ${{ env.DIST_CACHE_KEY }}

      - name: save build-cache
        uses: actions/cache/save@v3
        with:
          path: build
          key: ${{ env.BUILD_CACHE_KEY }}

  pack:
    needs: build
    runs-on: windows-latest
    env:
      DIST: ${{ needs.build.outputs.dist_dir }}
    steps:
      - name: restore cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.DIST }}
          key: ${{ env.DIST_CACHE_KEY }}
          fail-on-cache-miss: true

      - name: get release information
        id: get_info
        run: |
          $release = curl.exe -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" ${{env.api}} | ConvertFrom-Json

          [String] $prev_tag = $release[1].tag_name

          if ($prev_tag.Trim().Length -eq 0) {
              "comparation=''" >> $GITHUB_OUTPUT
              exit
          }

          $tag = (${{ github.ref }} -split '/')[-1]

          "comparation='**Full Changelog**: https://github.com/${{github.repository}}/compare/$prev_tag...$tag'" >> $GITHUB_OUTPUT

      - name: pack toolchain
        working-directory: ${{ env.DIST }}
        env:
          packed: ${{ env.PACKED_FILE }}
          digest: ${{ env.DIGEST_FILE }}
        run: |
          Get-ChildItem -Depth 1
          7z a -mmt -mx${{ env.COMPRESSION_LV }} -m0=BCJ2 -m1=${{ env.COMPRESSION_ALGO }} ${{env.packed}} rust9x
          sha256sum ${{env.packed}} > ${{env.digest}}

          foreach ($i in @("${{env.packed}}", "${{env.digest}}")) {
              Move-Item -Path $i -Destination ${{ github.workspace }} -Force
          }

      - name: release
        uses: softprops/action-gh-release@v1
        env:
          installation_url: https://github.com/rust9x/rust/wiki#installation
          comparation: ${{ steps.get_info.outputs.comparation }}
        with:
          prerelease: ${{ contains(fromJSON('["alpha", "beta", "rc"]'), github.ref) }}
          files: |
            ${{ env.PACKED_FILE }}
            ${{ env.DIGEST_FILE }}
          append_body: true
          body: |
            [Installation notes](${{env.installation_url}})

            ${{env.comparation}}
