name: build rust9x toolchain

env:
  BUILD_ARGS: "--incremental --verbose"
  PACKED_FILE: rust9x.7z
  COMPRESSION_LV: 5
  COMPRESSION_ALGO: LZMA2
  DIGEST_FILE: sha256sum.txt
  BUILD_CACHE_KEY: Windows-build
  DIST_CACHE_KEY: dist

on:
  push:
    tags:
      - "*.*"

jobs:
  preset:
    runs-on: windows-latest
    outputs:
      dist_dir: ${{ steps.get_dist_dir.outputs.dist }}
    steps:
      - name: get dist dir
        id: get_dist_dir
        run: |
          Set-Location -Path ..
          "dist=$(Get-Location)\dist" >> $GITHUB_OUTPUT
          Get-Content $GITHUB_OUTPUT

  # build:
  #   runs-on: windows-latest
  #   needs: preset
  #   env:
  #     DIST: ${{ needs.preset.outputs.dist_dir }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         # repository: rust9x/rust
  #         ref: rust9x
  #         fetch-depth: 50
  #         # submodules: true

  #     - name: restore build-cache
  #       id: cache-restore
  #       uses: actions/cache/restore@v3
  #       with:
  #         path: build
  #         key: ${{ env.BUILD_CACHE_KEY }}

  #     # If you don't remove the host symlink, then there will be a panic when building rust.
  #     # > panic message:
  #     #     thread 'main' panicked at src/lib.rs:476:13:
  #     #     fs::remove_dir(&host) failed with The directory name is invalid. (os error 267)
  #     - name: remove link & list directory
  #       continue-on-error: true
  #       run: |
  #         Remove-Item -Path build\host -Force
  #         Get-ChildItem -Depth 1 -Path build

  #     - name: build 9x
  #       run: |
  #         Copy-Item -Path config.rust9x.toml -Destination config.toml -Force
  #         python x.py install ${{ env.BUILD_ARGS }}

  #     - name: list the dist directory
  #       run: |
  #         Get-ChildItem -Depth 2 -Path ${{ env.DIST }}

  #     - name: delete old cache
  #       if: ${{ steps.cache-restore.outputs.cache-hit }}
  #       continue-on-error: true
  #       uses: MyAlbum/purge-cache@v2
  #       with:
  #         debug: true
  #         max-age: 60

  #     - name: save dist-cache
  #       uses: actions/cache/save@v3
  #       continue-on-error: false
  #       if: always()
  #       with:
  #         path: ${{ env.DIST }}
  #         key: ${{ env.DIST_CACHE_KEY }}

  #     - name: save build-cache
  #       uses: actions/cache/save@v3
  #       with:
  #         path: build
  #         key: ${{ env.BUILD_CACHE_KEY }}

  pack:
    # needs: [preset, build]
    needs: preset
    runs-on: windows-latest
    env:
      DIST: ${{ needs.preset.outputs.dist_dir }}
    steps:
      - name: restore cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.DIST }}
          key: ${{ env.DIST_CACHE_KEY }}
          fail-on-cache-miss: true

      - name: get release information
        id: get_info
        env:
          api_url: ${{ format('https://api.github.com/repos/{0}/releases', github.repository) }}
          api_header_0: "Accept: application/vnd.github+json"
          api_header_1: "X-GitHub-Api-Version: 2022-11-28"
        run: |
          $release = curl.exe -L -H "${{env.api_header_0}}" -H "${{env.api_header_1}}" "${{env.api_url}}" | ConvertFrom-Json

          [String] $prev_tag = $release[1].tag_name

          if ($prev_tag.Trim().Length -eq 0) {
              "comparation=''" >> $GITHUB_OUTPUT
              exit
          }

          $tag = (${{ github.ref }} -split '/')[-1]

          "comparation='**Full Changelog**: https://github.com/${{github.repository}}/compare/$prev_tag...$tag'" >> $GITHUB_OUTPUT

      # In the **dist** directory, package the **rust9x** folder in 7z format, compute its sha256 hash, and finally move the 7z and hash files to the `${{ github.workspace }}` directory.
      - name: pack toolchain
        working-directory: ${{ env.DIST }}
        env:
          packed: ${{ env.PACKED_FILE }}
          digest: ${{ env.DIGEST_FILE }}
          lv: ${{ env.COMPRESSION_LV }}
          algorithm: ${{ env.COMPRESSION_ALGO }}
          dir: rust9x
        run: |
          Get-ChildItem -Depth 1
          7z a -mmt -mx${{env.lv}} -m0=BCJ2 -m1=${{env.algorithm}} ${{env.packed}} ${{env.dir}}
          sha256sum ${{env.packed}} > ${{env.digest}}

          foreach ($i in @("${{env.packed}}", "${{env.digest}}")) {
              Move-Item -Path $i -Destination ${{ github.workspace }} -Force
          }

      - name: release
        uses: softprops/action-gh-release@v1
        env:
          installation_url: https://github.com/rust9x/rust/wiki#installation
          comparation: ${{ steps.get_info.outputs.comparation }}
        with:
          prerelease: ${{ contains(fromJSON('["alpha", "beta", "rc"]'), github.ref) }}
          files: |
            ${{ env.PACKED_FILE }}
            ${{ env.DIGEST_FILE }}
          append_body: true
          body: |
            [Installation notes](${{env.installation_url}})

            ${{env.comparation}}
